### ISSUE TITLE
Release v0.5.0

### ISSUE THREAD

**Issue by pinussilvestrus** [pinussilvestrus/vs-code-bpmn-io#7]
## Features to have | Bugs to fix

* [x] Show preview editor as option (syncing between panels) (https://github.com/pinussilvestrus/vs-code-bpmn-js-plugin/issues/1)
* [x] Set default canvas to white (https://github.com/pinussilvestrus/vs-code-bpmn-js-plugin/issues/3)
* [x] Show panels next to each other (https://github.com/pinussilvestrus/vs-code-bpmn-js-plugin/issues/6)
* [x] Use local dependencies in PreviewPanel (https://github.com/pinussilvestrus/vs-code-bpmn-io/issues/13)

## Further Tasks

* [ ] Update [`CHANGELOG`](https://github.com/pinussilvestrus/vs-code-bpmn-js-plugin/blob/master/CHANGELOG.md)
* [ ] Release `v0.5.0` to marketplace

**Comment by pinussilvestrus** [comment]
@salaboy I don't whether I have permissions to upload new versions to the marketplace, so maybe you will have to do it.

**Comment by salaboy** [comment]
@pinussilvestrus I have no idea how to do that... I can upload it .. but we definitely need to find a better way to do it.. 
Probably having a bpmn.io or Camunda account to make sure that the publisher is not me..

**Comment by pinussilvestrus** [comment]
Yes, we definitely have to decide on that. Let's discuss it soon.

**Comment by pinussilvestrus** [comment]
As any issue I planned for the v0.5.0 release are done by now, I could release it. (`vsce publish minor`).

**Comment by salaboy** [comment]
@pinussilvestrus go for it.. 
I will experiment with JX.. if you see some files being added to the root of the project don't worry too much.. I might remove them later.

**Comment by pinussilvestrus** [comment]
Alrighty 👍
